// Code generated by protoc-gen-go. DO NOT EDIT.
// source: geoaltsvc.proto

package geoaltsvc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateReq struct {
	UserId               uint32   `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Lat                  float64  `protobuf:"fixed64,2,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng                  float64  `protobuf:"fixed64,3,opt,name=lng,proto3" json:"lng,omitempty"`
	Message              string   `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateReq) Reset()         { *m = CreateReq{} }
func (m *CreateReq) String() string { return proto.CompactTextString(m) }
func (*CreateReq) ProtoMessage()    {}
func (*CreateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_geoaltsvc_574fd7bc6d7cef6a, []int{0}
}
func (m *CreateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateReq.Unmarshal(m, b)
}
func (m *CreateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateReq.Marshal(b, m, deterministic)
}
func (dst *CreateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateReq.Merge(dst, src)
}
func (m *CreateReq) XXX_Size() int {
	return xxx_messageInfo_CreateReq.Size(m)
}
func (m *CreateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateReq proto.InternalMessageInfo

func (m *CreateReq) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CreateReq) GetLat() float64 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *CreateReq) GetLng() float64 {
	if m != nil {
		return m.Lng
	}
	return 0
}

func (m *CreateReq) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type CreateResp struct {
	// Types that are valid to be assigned to Status:
	//	*CreateResp_Ok
	//	*CreateResp_Error
	Status               isCreateResp_Status `protobuf_oneof:"status"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *CreateResp) Reset()         { *m = CreateResp{} }
func (m *CreateResp) String() string { return proto.CompactTextString(m) }
func (*CreateResp) ProtoMessage()    {}
func (*CreateResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_geoaltsvc_574fd7bc6d7cef6a, []int{1}
}
func (m *CreateResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResp.Unmarshal(m, b)
}
func (m *CreateResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResp.Marshal(b, m, deterministic)
}
func (dst *CreateResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResp.Merge(dst, src)
}
func (m *CreateResp) XXX_Size() int {
	return xxx_messageInfo_CreateResp.Size(m)
}
func (m *CreateResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResp.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResp proto.InternalMessageInfo

type isCreateResp_Status interface {
	isCreateResp_Status()
}

type CreateResp_Ok struct {
	Ok bool `protobuf:"varint,1,opt,name=ok,proto3,oneof"`
}

type CreateResp_Error struct {
	Error string `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*CreateResp_Ok) isCreateResp_Status() {}

func (*CreateResp_Error) isCreateResp_Status() {}

func (m *CreateResp) GetStatus() isCreateResp_Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *CreateResp) GetOk() bool {
	if x, ok := m.GetStatus().(*CreateResp_Ok); ok {
		return x.Ok
	}
	return false
}

func (m *CreateResp) GetError() string {
	if x, ok := m.GetStatus().(*CreateResp_Error); ok {
		return x.Error
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*CreateResp) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _CreateResp_OneofMarshaler, _CreateResp_OneofUnmarshaler, _CreateResp_OneofSizer, []interface{}{
		(*CreateResp_Ok)(nil),
		(*CreateResp_Error)(nil),
	}
}

func _CreateResp_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*CreateResp)
	// status
	switch x := m.Status.(type) {
	case *CreateResp_Ok:
		t := uint64(0)
		if x.Ok {
			t = 1
		}
		b.EncodeVarint(1<<3 | proto.WireVarint)
		b.EncodeVarint(t)
	case *CreateResp_Error:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Error)
	case nil:
	default:
		return fmt.Errorf("CreateResp.Status has unexpected type %T", x)
	}
	return nil
}

func _CreateResp_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*CreateResp)
	switch tag {
	case 1: // status.ok
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Status = &CreateResp_Ok{x != 0}
		return true, err
	case 2: // status.error
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Status = &CreateResp_Error{x}
		return true, err
	default:
		return false, nil
	}
}

func _CreateResp_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*CreateResp)
	// status
	switch x := m.Status.(type) {
	case *CreateResp_Ok:
		n += 1 // tag and wire
		n += 1
	case *CreateResp_Error:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Error)))
		n += len(x.Error)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type GetAlertReq struct {
	UserId               uint32   `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Lat                  float64  `protobuf:"fixed64,2,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng                  float64  `protobuf:"fixed64,3,opt,name=lng,proto3" json:"lng,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAlertReq) Reset()         { *m = GetAlertReq{} }
func (m *GetAlertReq) String() string { return proto.CompactTextString(m) }
func (*GetAlertReq) ProtoMessage()    {}
func (*GetAlertReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_geoaltsvc_574fd7bc6d7cef6a, []int{2}
}
func (m *GetAlertReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAlertReq.Unmarshal(m, b)
}
func (m *GetAlertReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAlertReq.Marshal(b, m, deterministic)
}
func (dst *GetAlertReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAlertReq.Merge(dst, src)
}
func (m *GetAlertReq) XXX_Size() int {
	return xxx_messageInfo_GetAlertReq.Size(m)
}
func (m *GetAlertReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAlertReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetAlertReq proto.InternalMessageInfo

func (m *GetAlertReq) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *GetAlertReq) GetLat() float64 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *GetAlertReq) GetLng() float64 {
	if m != nil {
		return m.Lng
	}
	return 0
}

type GetAlertResp struct {
	Alerts               []*Alert `protobuf:"bytes,1,rep,name=alerts,proto3" json:"alerts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAlertResp) Reset()         { *m = GetAlertResp{} }
func (m *GetAlertResp) String() string { return proto.CompactTextString(m) }
func (*GetAlertResp) ProtoMessage()    {}
func (*GetAlertResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_geoaltsvc_574fd7bc6d7cef6a, []int{3}
}
func (m *GetAlertResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAlertResp.Unmarshal(m, b)
}
func (m *GetAlertResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAlertResp.Marshal(b, m, deterministic)
}
func (dst *GetAlertResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAlertResp.Merge(dst, src)
}
func (m *GetAlertResp) XXX_Size() int {
	return xxx_messageInfo_GetAlertResp.Size(m)
}
func (m *GetAlertResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAlertResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetAlertResp proto.InternalMessageInfo

func (m *GetAlertResp) GetAlerts() []*Alert {
	if m != nil {
		return m.Alerts
	}
	return nil
}

type Alert struct {
	Lat                  float64  `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng                  float64  `protobuf:"fixed64,2,opt,name=lng,proto3" json:"lng,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp            string   `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Alert) Reset()         { *m = Alert{} }
func (m *Alert) String() string { return proto.CompactTextString(m) }
func (*Alert) ProtoMessage()    {}
func (*Alert) Descriptor() ([]byte, []int) {
	return fileDescriptor_geoaltsvc_574fd7bc6d7cef6a, []int{4}
}
func (m *Alert) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Alert.Unmarshal(m, b)
}
func (m *Alert) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Alert.Marshal(b, m, deterministic)
}
func (dst *Alert) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Alert.Merge(dst, src)
}
func (m *Alert) XXX_Size() int {
	return xxx_messageInfo_Alert.Size(m)
}
func (m *Alert) XXX_DiscardUnknown() {
	xxx_messageInfo_Alert.DiscardUnknown(m)
}

var xxx_messageInfo_Alert proto.InternalMessageInfo

func (m *Alert) GetLat() float64 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *Alert) GetLng() float64 {
	if m != nil {
		return m.Lng
	}
	return 0
}

func (m *Alert) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Alert) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateReq)(nil), "CreateReq")
	proto.RegisterType((*CreateResp)(nil), "CreateResp")
	proto.RegisterType((*GetAlertReq)(nil), "GetAlertReq")
	proto.RegisterType((*GetAlertResp)(nil), "GetAlertResp")
	proto.RegisterType((*Alert)(nil), "Alert")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GeoAltClient is the client API for GeoAlt service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GeoAltClient interface {
	CreateAlert(ctx context.Context, in *CreateReq, opts ...grpc.CallOption) (*CreateResp, error)
	GetAlert(ctx context.Context, in *GetAlertReq, opts ...grpc.CallOption) (*GetAlertResp, error)
}

type geoAltClient struct {
	cc *grpc.ClientConn
}

func NewGeoAltClient(cc *grpc.ClientConn) GeoAltClient {
	return &geoAltClient{cc}
}

func (c *geoAltClient) CreateAlert(ctx context.Context, in *CreateReq, opts ...grpc.CallOption) (*CreateResp, error) {
	out := new(CreateResp)
	err := c.cc.Invoke(ctx, "/GeoAlt/CreateAlert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geoAltClient) GetAlert(ctx context.Context, in *GetAlertReq, opts ...grpc.CallOption) (*GetAlertResp, error) {
	out := new(GetAlertResp)
	err := c.cc.Invoke(ctx, "/GeoAlt/GetAlert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GeoAltServer is the server API for GeoAlt service.
type GeoAltServer interface {
	CreateAlert(context.Context, *CreateReq) (*CreateResp, error)
	GetAlert(context.Context, *GetAlertReq) (*GetAlertResp, error)
}

func RegisterGeoAltServer(s *grpc.Server, srv GeoAltServer) {
	s.RegisterService(&_GeoAlt_serviceDesc, srv)
}

func _GeoAlt_CreateAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeoAltServer).CreateAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GeoAlt/CreateAlert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeoAltServer).CreateAlert(ctx, req.(*CreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeoAlt_GetAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAlertReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeoAltServer).GetAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GeoAlt/GetAlert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeoAltServer).GetAlert(ctx, req.(*GetAlertReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _GeoAlt_serviceDesc = grpc.ServiceDesc{
	ServiceName: "GeoAlt",
	HandlerType: (*GeoAltServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAlert",
			Handler:    _GeoAlt_CreateAlert_Handler,
		},
		{
			MethodName: "GetAlert",
			Handler:    _GeoAlt_GetAlert_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "geoaltsvc.proto",
}

func init() { proto.RegisterFile("geoaltsvc.proto", fileDescriptor_geoaltsvc_574fd7bc6d7cef6a) }

var fileDescriptor_geoaltsvc_574fd7bc6d7cef6a = []byte{
	// 284 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x91, 0x4d, 0x4f, 0xc2, 0x40,
	0x10, 0x86, 0xd9, 0x56, 0x16, 0x3a, 0x85, 0x48, 0xf6, 0xa0, 0x1b, 0x62, 0x4c, 0xd3, 0x83, 0xf6,
	0xb4, 0x07, 0xfc, 0x03, 0xa2, 0x07, 0xd0, 0xe3, 0xde, 0x3c, 0x99, 0x05, 0x26, 0x0d, 0xa1, 0xb0,
	0x75, 0x77, 0xf0, 0xf7, 0x1b, 0xfa, 0x21, 0x35, 0x7a, 0xf3, 0xd6, 0xf7, 0x6d, 0xf2, 0xcc, 0xce,
	0x33, 0x70, 0x99, 0xa3, 0x35, 0x05, 0xf9, 0xcf, 0xb5, 0x2a, 0x9d, 0x25, 0x9b, 0xae, 0x20, 0x7a,
	0x76, 0x68, 0x08, 0x35, 0x7e, 0x88, 0x6b, 0x18, 0x1c, 0x3d, 0xba, 0xf7, 0xed, 0x46, 0xb2, 0x84,
	0x65, 0x63, 0xcd, 0x4f, 0xf1, 0x65, 0x23, 0x26, 0x10, 0x16, 0x86, 0x64, 0x90, 0xb0, 0x8c, 0xe9,
	0xd3, 0x67, 0xd5, 0x1c, 0x72, 0x19, 0x36, 0xcd, 0x21, 0x17, 0x12, 0x06, 0x7b, 0xf4, 0xde, 0xe4,
	0x28, 0x2f, 0x12, 0x96, 0x45, 0xba, 0x8d, 0xe9, 0x23, 0x40, 0x3b, 0xc3, 0x97, 0x62, 0x02, 0x81,
	0xdd, 0x55, 0xfc, 0xe1, 0xb2, 0xa7, 0x03, 0xbb, 0x13, 0x57, 0xd0, 0x47, 0xe7, 0xac, 0xab, 0xf8,
	0xd1, 0xb2, 0xa7, 0xeb, 0xf8, 0x34, 0x04, 0xee, 0xc9, 0xd0, 0xd1, 0xa7, 0xaf, 0x10, 0x2f, 0x90,
	0xe6, 0x05, 0x3a, 0xfa, 0xef, 0x3b, 0x53, 0x05, 0xa3, 0x33, 0xcb, 0x97, 0xe2, 0x16, 0xb8, 0x39,
	0x05, 0x2f, 0x59, 0x12, 0x66, 0xf1, 0x8c, 0xab, 0xfa, 0x5f, 0xd3, 0xa6, 0x6b, 0xe8, 0x57, 0x45,
	0x0b, 0x67, 0xbf, 0xe0, 0xc1, 0x9f, 0x12, 0xc2, 0x1f, 0x12, 0xc4, 0x0d, 0x44, 0xb4, 0xdd, 0xa3,
	0x27, 0xb3, 0x2f, 0x1b, 0x41, 0xe7, 0x62, 0xf6, 0x06, 0x7c, 0x81, 0x76, 0x5e, 0x90, 0xb8, 0x83,
	0xb8, 0x96, 0x55, 0x0f, 0x05, 0xf5, 0x7d, 0x9e, 0x69, 0xac, 0x3a, 0x1a, 0xef, 0x61, 0xd8, 0xae,
	0x21, 0x46, 0xaa, 0x63, 0x67, 0x3a, 0x56, 0xdd, 0xfd, 0x56, 0xbc, 0x3a, 0xf4, 0xc3, 0x57, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x90, 0x9f, 0x7c, 0xed, 0xfb, 0x01, 0x00, 0x00,
}
