// Code generated by protoc-gen-go. DO NOT EDIT.
// source: geoaltsvc.proto

package geoaltsvc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RegisterReq struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	FirstName            string   `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Address              string   `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterReq) Reset()         { *m = RegisterReq{} }
func (m *RegisterReq) String() string { return proto.CompactTextString(m) }
func (*RegisterReq) ProtoMessage()    {}
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_geoaltsvc_ccec547fd199d24b, []int{0}
}
func (m *RegisterReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterReq.Unmarshal(m, b)
}
func (m *RegisterReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterReq.Marshal(b, m, deterministic)
}
func (dst *RegisterReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterReq.Merge(dst, src)
}
func (m *RegisterReq) XXX_Size() int {
	return xxx_messageInfo_RegisterReq.Size(m)
}
func (m *RegisterReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterReq.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterReq proto.InternalMessageInfo

func (m *RegisterReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterReq) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *RegisterReq) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *RegisterReq) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type RegisterResp struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResp) Reset()         { *m = RegisterResp{} }
func (m *RegisterResp) String() string { return proto.CompactTextString(m) }
func (*RegisterResp) ProtoMessage()    {}
func (*RegisterResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_geoaltsvc_ccec547fd199d24b, []int{1}
}
func (m *RegisterResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResp.Unmarshal(m, b)
}
func (m *RegisterResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResp.Marshal(b, m, deterministic)
}
func (dst *RegisterResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResp.Merge(dst, src)
}
func (m *RegisterResp) XXX_Size() int {
	return xxx_messageInfo_RegisterResp.Size(m)
}
func (m *RegisterResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResp.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResp proto.InternalMessageInfo

func (m *RegisterResp) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type LoginReq struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_geoaltsvc_ccec547fd199d24b, []int{2}
}
func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (dst *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(dst, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResp struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResp) Reset()         { *m = LoginResp{} }
func (m *LoginResp) String() string { return proto.CompactTextString(m) }
func (*LoginResp) ProtoMessage()    {}
func (*LoginResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_geoaltsvc_ccec547fd199d24b, []int{3}
}
func (m *LoginResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResp.Unmarshal(m, b)
}
func (m *LoginResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResp.Marshal(b, m, deterministic)
}
func (dst *LoginResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResp.Merge(dst, src)
}
func (m *LoginResp) XXX_Size() int {
	return xxx_messageInfo_LoginResp.Size(m)
}
func (m *LoginResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResp.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResp proto.InternalMessageInfo

func (m *LoginResp) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type CreateAlertReq struct {
	UserId               uint32   `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Lat                  float64  `protobuf:"fixed64,2,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng                  float64  `protobuf:"fixed64,3,opt,name=lng,proto3" json:"lng,omitempty"`
	Message              string   `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Ephemeral            bool     `protobuf:"varint,5,opt,name=ephemeral,proto3" json:"ephemeral,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAlertReq) Reset()         { *m = CreateAlertReq{} }
func (m *CreateAlertReq) String() string { return proto.CompactTextString(m) }
func (*CreateAlertReq) ProtoMessage()    {}
func (*CreateAlertReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_geoaltsvc_ccec547fd199d24b, []int{4}
}
func (m *CreateAlertReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAlertReq.Unmarshal(m, b)
}
func (m *CreateAlertReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAlertReq.Marshal(b, m, deterministic)
}
func (dst *CreateAlertReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAlertReq.Merge(dst, src)
}
func (m *CreateAlertReq) XXX_Size() int {
	return xxx_messageInfo_CreateAlertReq.Size(m)
}
func (m *CreateAlertReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAlertReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAlertReq proto.InternalMessageInfo

func (m *CreateAlertReq) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CreateAlertReq) GetLat() float64 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *CreateAlertReq) GetLng() float64 {
	if m != nil {
		return m.Lng
	}
	return 0
}

func (m *CreateAlertReq) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *CreateAlertReq) GetEphemeral() bool {
	if m != nil {
		return m.Ephemeral
	}
	return false
}

type CreateAlertResp struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAlertResp) Reset()         { *m = CreateAlertResp{} }
func (m *CreateAlertResp) String() string { return proto.CompactTextString(m) }
func (*CreateAlertResp) ProtoMessage()    {}
func (*CreateAlertResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_geoaltsvc_ccec547fd199d24b, []int{5}
}
func (m *CreateAlertResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAlertResp.Unmarshal(m, b)
}
func (m *CreateAlertResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAlertResp.Marshal(b, m, deterministic)
}
func (dst *CreateAlertResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAlertResp.Merge(dst, src)
}
func (m *CreateAlertResp) XXX_Size() int {
	return xxx_messageInfo_CreateAlertResp.Size(m)
}
func (m *CreateAlertResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAlertResp.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAlertResp proto.InternalMessageInfo

func (m *CreateAlertResp) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type GetAlertReq struct {
	UserId               uint32   `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Lat                  float64  `protobuf:"fixed64,2,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng                  float64  `protobuf:"fixed64,3,opt,name=lng,proto3" json:"lng,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAlertReq) Reset()         { *m = GetAlertReq{} }
func (m *GetAlertReq) String() string { return proto.CompactTextString(m) }
func (*GetAlertReq) ProtoMessage()    {}
func (*GetAlertReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_geoaltsvc_ccec547fd199d24b, []int{6}
}
func (m *GetAlertReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAlertReq.Unmarshal(m, b)
}
func (m *GetAlertReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAlertReq.Marshal(b, m, deterministic)
}
func (dst *GetAlertReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAlertReq.Merge(dst, src)
}
func (m *GetAlertReq) XXX_Size() int {
	return xxx_messageInfo_GetAlertReq.Size(m)
}
func (m *GetAlertReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAlertReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetAlertReq proto.InternalMessageInfo

func (m *GetAlertReq) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *GetAlertReq) GetLat() float64 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *GetAlertReq) GetLng() float64 {
	if m != nil {
		return m.Lng
	}
	return 0
}

type GetAlertResp struct {
	Alerts               []*Alert `protobuf:"bytes,1,rep,name=alerts,proto3" json:"alerts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAlertResp) Reset()         { *m = GetAlertResp{} }
func (m *GetAlertResp) String() string { return proto.CompactTextString(m) }
func (*GetAlertResp) ProtoMessage()    {}
func (*GetAlertResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_geoaltsvc_ccec547fd199d24b, []int{7}
}
func (m *GetAlertResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAlertResp.Unmarshal(m, b)
}
func (m *GetAlertResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAlertResp.Marshal(b, m, deterministic)
}
func (dst *GetAlertResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAlertResp.Merge(dst, src)
}
func (m *GetAlertResp) XXX_Size() int {
	return xxx_messageInfo_GetAlertResp.Size(m)
}
func (m *GetAlertResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAlertResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetAlertResp proto.InternalMessageInfo

func (m *GetAlertResp) GetAlerts() []*Alert {
	if m != nil {
		return m.Alerts
	}
	return nil
}

type Alert struct {
	Center               *Coord   `protobuf:"bytes,1,opt,name=center,proto3" json:"center,omitempty"`
	Borders              []*Coord `protobuf:"bytes,2,rep,name=borders,proto3" json:"borders,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp            string   `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Alert) Reset()         { *m = Alert{} }
func (m *Alert) String() string { return proto.CompactTextString(m) }
func (*Alert) ProtoMessage()    {}
func (*Alert) Descriptor() ([]byte, []int) {
	return fileDescriptor_geoaltsvc_ccec547fd199d24b, []int{8}
}
func (m *Alert) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Alert.Unmarshal(m, b)
}
func (m *Alert) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Alert.Marshal(b, m, deterministic)
}
func (dst *Alert) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Alert.Merge(dst, src)
}
func (m *Alert) XXX_Size() int {
	return xxx_messageInfo_Alert.Size(m)
}
func (m *Alert) XXX_DiscardUnknown() {
	xxx_messageInfo_Alert.DiscardUnknown(m)
}

var xxx_messageInfo_Alert proto.InternalMessageInfo

func (m *Alert) GetCenter() *Coord {
	if m != nil {
		return m.Center
	}
	return nil
}

func (m *Alert) GetBorders() []*Coord {
	if m != nil {
		return m.Borders
	}
	return nil
}

func (m *Alert) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Alert) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

type Coord struct {
	Lat                  float64  `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng                  float64  `protobuf:"fixed64,2,opt,name=lng,proto3" json:"lng,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Coord) Reset()         { *m = Coord{} }
func (m *Coord) String() string { return proto.CompactTextString(m) }
func (*Coord) ProtoMessage()    {}
func (*Coord) Descriptor() ([]byte, []int) {
	return fileDescriptor_geoaltsvc_ccec547fd199d24b, []int{9}
}
func (m *Coord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Coord.Unmarshal(m, b)
}
func (m *Coord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Coord.Marshal(b, m, deterministic)
}
func (dst *Coord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Coord.Merge(dst, src)
}
func (m *Coord) XXX_Size() int {
	return xxx_messageInfo_Coord.Size(m)
}
func (m *Coord) XXX_DiscardUnknown() {
	xxx_messageInfo_Coord.DiscardUnknown(m)
}

var xxx_messageInfo_Coord proto.InternalMessageInfo

func (m *Coord) GetLat() float64 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *Coord) GetLng() float64 {
	if m != nil {
		return m.Lng
	}
	return 0
}

func init() {
	proto.RegisterType((*RegisterReq)(nil), "RegisterReq")
	proto.RegisterType((*RegisterResp)(nil), "RegisterResp")
	proto.RegisterType((*LoginReq)(nil), "LoginReq")
	proto.RegisterType((*LoginResp)(nil), "LoginResp")
	proto.RegisterType((*CreateAlertReq)(nil), "CreateAlertReq")
	proto.RegisterType((*CreateAlertResp)(nil), "CreateAlertResp")
	proto.RegisterType((*GetAlertReq)(nil), "GetAlertReq")
	proto.RegisterType((*GetAlertResp)(nil), "GetAlertResp")
	proto.RegisterType((*Alert)(nil), "Alert")
	proto.RegisterType((*Coord)(nil), "Coord")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GeoAltClient is the client API for GeoAlt service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GeoAltClient interface {
	Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
	Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error)
	CreateAlert(ctx context.Context, in *CreateAlertReq, opts ...grpc.CallOption) (*CreateAlertResp, error)
	GetAlert(ctx context.Context, in *GetAlertReq, opts ...grpc.CallOption) (*GetAlertResp, error)
}

type geoAltClient struct {
	cc *grpc.ClientConn
}

func NewGeoAltClient(cc *grpc.ClientConn) GeoAltClient {
	return &geoAltClient{cc}
}

func (c *geoAltClient) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	out := new(LoginResp)
	err := c.cc.Invoke(ctx, "/GeoAlt/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geoAltClient) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error) {
	out := new(RegisterResp)
	err := c.cc.Invoke(ctx, "/GeoAlt/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geoAltClient) CreateAlert(ctx context.Context, in *CreateAlertReq, opts ...grpc.CallOption) (*CreateAlertResp, error) {
	out := new(CreateAlertResp)
	err := c.cc.Invoke(ctx, "/GeoAlt/CreateAlert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geoAltClient) GetAlert(ctx context.Context, in *GetAlertReq, opts ...grpc.CallOption) (*GetAlertResp, error) {
	out := new(GetAlertResp)
	err := c.cc.Invoke(ctx, "/GeoAlt/GetAlert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GeoAltServer is the server API for GeoAlt service.
type GeoAltServer interface {
	Login(context.Context, *LoginReq) (*LoginResp, error)
	Register(context.Context, *RegisterReq) (*RegisterResp, error)
	CreateAlert(context.Context, *CreateAlertReq) (*CreateAlertResp, error)
	GetAlert(context.Context, *GetAlertReq) (*GetAlertResp, error)
}

func RegisterGeoAltServer(s *grpc.Server, srv GeoAltServer) {
	s.RegisterService(&_GeoAlt_serviceDesc, srv)
}

func _GeoAlt_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeoAltServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GeoAlt/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeoAltServer).Login(ctx, req.(*LoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeoAlt_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeoAltServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GeoAlt/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeoAltServer).Register(ctx, req.(*RegisterReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeoAlt_CreateAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAlertReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeoAltServer).CreateAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GeoAlt/CreateAlert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeoAltServer).CreateAlert(ctx, req.(*CreateAlertReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeoAlt_GetAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAlertReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeoAltServer).GetAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GeoAlt/GetAlert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeoAltServer).GetAlert(ctx, req.(*GetAlertReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _GeoAlt_serviceDesc = grpc.ServiceDesc{
	ServiceName: "GeoAlt",
	HandlerType: (*GeoAltServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _GeoAlt_Login_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _GeoAlt_Register_Handler,
		},
		{
			MethodName: "CreateAlert",
			Handler:    _GeoAlt_CreateAlert_Handler,
		},
		{
			MethodName: "GetAlert",
			Handler:    _GeoAlt_GetAlert_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "geoaltsvc.proto",
}

func init() { proto.RegisterFile("geoaltsvc.proto", fileDescriptor_geoaltsvc_ccec547fd199d24b) }

var fileDescriptor_geoaltsvc_ccec547fd199d24b = []byte{
	// 455 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0x4d, 0x6f, 0xd4, 0x30,
	0x10, 0x95, 0x77, 0x49, 0x36, 0x99, 0xdd, 0xed, 0x56, 0x16, 0x12, 0x51, 0xf8, 0xd0, 0xd6, 0x42,
	0x6a, 0x25, 0x24, 0x0b, 0x95, 0x2b, 0x97, 0xaa, 0x87, 0x0a, 0x84, 0x38, 0xe4, 0x0f, 0x54, 0x6e,
	0x33, 0x84, 0x68, 0x93, 0x38, 0xd8, 0x06, 0xce, 0x1c, 0xf8, 0x09, 0xfc, 0x0b, 0x7e, 0x24, 0xf2,
	0x6c, 0xdc, 0x64, 0xa9, 0xb8, 0xa0, 0xde, 0xf2, 0xde, 0x4c, 0x3c, 0x6f, 0x9e, 0x9f, 0x61, 0x53,
	0xa1, 0x56, 0x8d, 0xb3, 0xdf, 0x6e, 0x65, 0x6f, 0xb4, 0xd3, 0xe2, 0x17, 0x83, 0x65, 0x81, 0x55,
	0x6d, 0x1d, 0x9a, 0x02, 0xbf, 0xf0, 0xc7, 0x10, 0x61, 0xab, 0xea, 0x26, 0x63, 0x5b, 0x76, 0x96,
	0x16, 0x7b, 0xc0, 0x73, 0x48, 0x7a, 0x65, 0xed, 0x77, 0x6d, 0xca, 0x6c, 0x46, 0x85, 0x3b, 0xcc,
	0x9f, 0x03, 0x7c, 0xaa, 0x8d, 0x75, 0xd7, 0x9d, 0x6a, 0x31, 0x9b, 0x53, 0x35, 0x25, 0xe6, 0xa3,
	0x6a, 0x91, 0x3f, 0x85, 0xb4, 0x51, 0xa1, 0xfa, 0x68, 0xff, 0xaf, 0x27, 0xa8, 0x98, 0xc1, 0x42,
	0x95, 0xa5, 0x41, 0x6b, 0xb3, 0x88, 0x4a, 0x01, 0x8a, 0x97, 0xb0, 0x1a, 0x65, 0xd9, 0xde, 0xeb,
	0x72, 0x7a, 0x87, 0x5d, 0xd0, 0x45, 0x40, 0xbc, 0x85, 0xe4, 0x83, 0xae, 0xea, 0xee, 0xbf, 0x94,
	0x8b, 0x13, 0x48, 0x87, 0xbf, 0xff, 0x39, 0xe0, 0x27, 0x83, 0xa3, 0x4b, 0x83, 0xca, 0xe1, 0x45,
	0x83, 0xc6, 0xf9, 0x39, 0x4f, 0x60, 0xf1, 0xd5, 0xa2, 0xb9, 0xae, 0x4b, 0x6a, 0x5d, 0x17, 0xb1,
	0x87, 0xef, 0x4a, 0x7e, 0x0c, 0xf3, 0x46, 0x39, 0x9a, 0xc2, 0x0a, 0xff, 0x49, 0x4c, 0x57, 0x91,
	0x27, 0x9e, 0xe9, 0x2a, 0xbf, 0x70, 0x8b, 0xd6, 0xaa, 0x2a, 0x78, 0x11, 0x20, 0x7f, 0x06, 0x29,
	0xf6, 0x9f, 0xb1, 0x45, 0xa3, 0x1a, 0x32, 0x23, 0x29, 0x46, 0x42, 0x9c, 0xc0, 0xe6, 0x40, 0x86,
	0xed, 0xf9, 0x11, 0xcc, 0xf4, 0x8e, 0x24, 0x24, 0xc5, 0x4c, 0xef, 0xc4, 0x7b, 0x58, 0x5e, 0xa1,
	0x7b, 0x10, 0x99, 0x42, 0xc2, 0x6a, 0x3c, 0xcb, 0xf6, 0xfc, 0x05, 0xc4, 0xca, 0x03, 0x9b, 0xb1,
	0xed, 0xfc, 0x6c, 0x79, 0x1e, 0xcb, 0x7d, 0x6d, 0x60, 0xc5, 0x0f, 0x06, 0x11, 0x31, 0xbe, 0xf3,
	0x16, 0x3b, 0x87, 0x86, 0xa6, 0xfa, 0xce, 0x4b, 0xad, 0x4d, 0x59, 0x0c, 0x2c, 0xdf, 0xc2, 0xe2,
	0x46, 0x9b, 0x12, 0x8d, 0xcd, 0x66, 0xc3, 0x51, 0xfb, 0x86, 0x40, 0x4f, 0x2d, 0x9a, 0xdf, 0xb3,
	0xc8, 0xd5, 0x2d, 0x5a, 0xa7, 0xda, 0x7e, 0xb0, 0x6f, 0x24, 0xc4, 0x2b, 0x88, 0xe8, 0xa4, 0xb0,
	0x20, 0xbb, 0xb7, 0xe0, 0xec, 0x6e, 0xc1, 0xf3, 0xdf, 0x0c, 0xe2, 0x2b, 0xd4, 0x17, 0x8d, 0x57,
	0x1c, 0x51, 0x0a, 0x78, 0x2a, 0x43, 0x96, 0x72, 0x90, 0x63, 0x30, 0x4e, 0x21, 0x09, 0x49, 0xe4,
	0x2b, 0x39, 0x79, 0x2b, 0xf9, 0x5a, 0x1e, 0x44, 0xf4, 0x35, 0x2c, 0x27, 0x77, 0xc4, 0x37, 0xf2,
	0x30, 0x38, 0xf9, 0xb1, 0xfc, 0xfb, 0x0a, 0x4f, 0x21, 0x09, 0x36, 0xf3, 0x95, 0x9c, 0xdc, 0x5e,
	0xbe, 0x96, 0x53, 0xff, 0x6f, 0x62, 0x7a, 0xac, 0x6f, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0xf6,
	0xaf, 0x62, 0x90, 0xbf, 0x03, 0x00, 0x00,
}
